### ISSUE TITLE
Cpp question about constructor syntax

### ISSUE THREAD

**Issue by TK-21st** [ja3067/Titan#10]
In the `spring.h` code, there appear to be multiple constructor definitions. I want to ask about the syntax in the last 3 definitions. 
```c++
    Spring() { _left = nullptr; _right = nullptr; arrayptr = nullptr; _rest = 1.0; _k = 10000.0; }
    
    Spring(const CUDA_SPRING & spr);

    Spring(Mass * left, Mass * right, double k = 10000.0, double rest_len = 1.0) :
            _k(k), _rest(rest_len), _left(left), _right(right), arrayptr(nullptr) {}; //

    Spring(double k, double rest_length, Mass * left, Mass * right) :
            _k(k), _rest(rest_length), _left(left), _right(right) {};

    Spring(Mass * left, Mass * right, double k = 10000.0, double rest_len = 1.0) :
            _k(k), _rest(rest_len), _left(left), _right(right), arrayptr(nullptr) {}; //
```

For example, what does `    Spring(double k, double rest_length, Mass * left, Mass * right) :
            _k(k), _rest(rest_length), _left(left), _right(right) {};` mean? what does `_k(k)` mean in this context?

**Comment by jacobaustin123** [comment]
This is a C++11 syntax that simplifies constructors which simply set class fields. _k(k) means set the variable _k to the value of k given to the constructor (which is defaulted to 10000.0, but can be changed by the user). {} means to do nothing besides setting the values specified using the previous syntax.
