### ISSUE TITLE
Accessing simulation time from CUDA kernel

### ISSUE THREAD

**Issue by TK-21st** [ja3067/Titan#12]
I want to implement something like

```
double rest_length = spring -> _rest * (1 + spring -> a * sin(spring -> omega* sim -> T + spring- > b));
```

This will set the cube to have breathing behavior by changing the rest length in a sinusoidal fashion. However, such functions require access to simulation time `sim->T`. I could add a private variable `T` to each spring that copies the global `T`,  but is there a better way to do this?

**Comment by jacobaustin123** [comment]
No there is not, unless you pass T to each instance of the kernel. This is because T is stored as a CPU class variable, and isn't accessible to the strings. This seems to be the route you've taken, which I approve of. Be aware that passing to kernels can have some overhead.
