### ISSUE TITLE
`Simulation::start()` expects 0 argument

### ISSUE THREAD

**Issue by TK-21st** [ja3067/Titan#2]
As title. The example code is uses `sim.start(10)` for simulation lasting 10 seconds.

`Simulation::start()` in `Titan/include/sim.h` expects no argument.

**Comment by jacobaustin123** [comment]
I believe we changed the API to expect start() to take no arguments. You can set breakpoints (sim.setBreakpoint(float time)) or manually stop the program (sim.stop()) to end it.

**Comment by TK-21st** [comment]
@ja3067 Yep! Just opened the issue because the examples still refer to the old API. Edited the issue above accordingly.

**Comment by jacobaustin123** [comment]
Thanks. I think we've fixed the wiki. Let me know if you still see it in one of the tutorials.
