### ISSUE TITLE
windows install error (link lib)

### ISSUE THREAD

**Issue by EdvrSoft** [ja3067/Titan#24]
I'm not able to install Titan on windows. 

I follow the steps from https://jacobaustin123.github.io/Titan/. but I get a link error: 

`LINK : fatal error LNK1104: cannot open file 'glm.lib'`

I attach log error:

[install-x64-windows-dbg-out.log](https://github.com/jacobaustin123/Titan/files/6371023/install-x64-windows-dbg-out.log)

- Cuda compilation tools, release 10.1, V10.1.243
- Vcpkg:  2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
- Visual studio 2017
- C/C++ Optimizing Compiler: 19.16.27045
- link: 14.16.27045.0

I see step 8 is ok. nvcc sees glm.lib, but link.exe couldn't

thanks!

**Comment by jacobaustin123** [comment]
Hi. Could you try running `vcpkg install glm`? If that succeeds, you might need to add a line like `find_path(GLM_PATH glm/glm.h)` to the CMakeLists.txt file (or some variant of that, to tell vcpkg where to find GLM).

**Comment by EdvrSoft** [comment]
Hi,

I replaced "[target_link_libraries(Titan PRIVATE ${glm_LIBRARIES} glm)](https://github.com/jacobaustin123/Titan/blob/5edba2e01b0a20e20cb3bcf094cbe953f148f002/CMakeLists.txt#L169)" with "target_link_libraries(Titan PRIVATE ${glm_LIBRARIES} **glm::glm**)" and it works. 

I don't know what is the difference between "glm" and "glm::glm" in cmake context. 

thanks!
