### ISSUE TITLE
Windows installation failure

### ISSUE THREAD

**Issue by princexprincess** [ja3067/Titan#5]
I encountered a problem when installing titan in vcpkg. 

The command line shows the following error:
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/titan/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\titan\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/titan/portfile.cmake:60 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

The install-x64-windows-dbg-out.log shows the following error:
......
c:\vcpkg\installed\x64-windows\include\glm\detail/type_vec1.hpp(132): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

c:\vcpkg\installed\x64-windows\include\glm\detail/qualifier.hpp(104): error: attributes are not allowed here
          detected during:
            instantiation of class "glm::detail::storage<3, T, true> [with T=float]" 
c:\vcpkg\installed\x64-windows\include\glm\ext\../detail/type_vec3.hpp(53): here
            instantiation of class "glm::vec<3, T, Q> [with T=float, Q=glm::aligned_lowp]" 
c:\vcpkg\installed\x64-windows\include\glm\ext\../detail/type_mat4x3.hpp(23): here
            instantiation of class "glm::mat<4, 3, T, Q> [with T=float, Q=glm::aligned_lowp]" 
c:\vcpkg\installed\x64-windows\include\glm\detail\func_matrix_simd.inl(69): here

c:\vcpkg\installed\x64-windows\include\glm\detail/qualifier.hpp(96): error: attributes are not allowed here
          detected during:
            instantiation of class "glm::detail::storage<L, T, true> [with L=2, T=float]" 
c:\vcpkg\installed\x64-windows\include\glm\ext\../detail/type_vec2.hpp(50): here
            instantiation of class "glm::vec<2, T, Q> [with T=float, Q=glm::aligned_lowp]" 
c:\vcpkg\installed\x64-windows\include\glm\ext\../detail/type_mat4x2.hpp(23): here
            instantiation of class "glm::mat<4, 2, T, Q> [with T=float, Q=glm::aligned_lowp]" 
c:\vcpkg\installed\x64-windows\include\glm\detail\func_matrix_simd.inl(69): here

C:/vcpkg/buildtrees/titan/src/420888144f-fb31a06eb3/src/sim.cu(71): warning: statement is unreachable

2 errors detected in the compilation of "C:/Users/mashi/AppData/Local/Temp/tmpxft_00004564_00000000-10_sim.cpp1.ii".
sim.cu
ninja: build stopped: subcommand failed.

Can't find a way to fix it.

**Comment by jacobaustin123** [comment]
We believe the issue was fixed in this issue. Try following the instructions in this post, and let us know if it's still an issue. https://github.com/ja3067/Titan/issues/4

**Comment by rcorralesf** [comment]
The user reports the issue has been resolved.
